spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console.enabled: true
  
server:
  port: 8081


servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
 
mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: kpds0932@gmail.com
    password: Pravu@1610
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

