spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  datasource:
    username: nb_rms
    url: jdbc:oracle:thin:@192.168.2.111:1522:ORCL
    driverClassName: oracle.jdbc.driver.OracleDriver
    password: nb_rms
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true       
server:
  port: 8081 


