spring:
  datasource:
    url: jdbc:h2:mem:testdb  # JDBC URL for H2 in-memory database
    driver-class-name: org.h2.Driver  # H2 database driver class
    username: sa  # Default username
    password: sa # Default password
  h2:
    console:
      enabled: true  # Enable H2 console
  jpa:
    hibernate:
      ddl-auto: create-drop  # Hibernate DDL auto configuration
    show-sql: true  # Show SQL statements in logs

# Optionally, you can set additional JPA properties
    properties:
     hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       format_sql: true
#      use_sql_comments: true